-- MySQL Script generated by MySQL Workbench
-- Tue Dec 14 10:02:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lgzrohke_nouser_url
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lgzrohke_nouser_url
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lgzrohke_nouser_url` DEFAULT CHARACTER SET utf8 ;
USE `lgzrohke_nouser_url` ;

-- -----------------------------------------------------
-- Table `lgzrohke_nouser_url`.`url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lgzrohke_nouser_url`.`url` (
  `shorturl` varchar(10) NOT NULL,
  `longurl` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`shorturl`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
