-- MySQL Script generated by MySQL Workbench
-- Thu Dec  9 08:45:19 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema shorturl
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shorturl
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lgzrohke_shorturl` DEFAULT CHARACTER SET latin1 ;
USE `lgzrohke_shorturl` ;

-- -----------------------------------------------------
-- Table `lgzrohke_shorturl`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lgzrohke_shorturl`.`user` (
  `userid` INT(4) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lgzrohke_shorturl`.`url`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lgzrohke_shorturl`.`url` (
  `longurl` VARCHAR(200) NOT NULL,
  `user_userid` INT(4) NOT NULL,
  `shorturl` TEXT NOT NULL,
  PRIMARY KEY (`longurl`, `user_userid`),
  INDEX `fk_url_user_idx` (`user_userid` ASC),
  CONSTRAINT `fk_url_user`
    FOREIGN KEY (`user_userid`)
    REFERENCES `lgzrohke_shorturl`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
